Upstream  4k/dpi awareness Tool fixes
dhewm/dhewm3 pull request #339
Opened 2021-01-15 22:46 UTC by HarrievG

Contains all fixes in tool-land to draw and size all window elements  in editor windows when DPI settings are used.

Also contains modified cmaketexts. Only SDL part is important now. Keep added settings off until until integration is comple, or take only the changes in tool. 

-H.

2021-01-16 00:49 UTC, DanielGibson commented
Could you rebase this on current master (to get rid of the merge conflicts) and clean it up a bit?
There's lots of unrelated changes in CMakeLists.txt and half of the commits are merge commits (maybe rebasing would already get rid of those?)

2021-01-16 01:17 UTC, HarrievG commented
Hi Daniel, 
Yes will try to rebase, then also the 2 defines in the tool code (.dae) related can go for this base. And it's cleaner in the cmake too. Sorry I am not as git savvy as I want to be ;)

???: I put the remake there to not forgot to check sdl2 cmake setup, I had to fix something there. The fix is in and discussed on rbdoombfg issue page 

_afxdll: ah yes, MFC ! That is referencing it somewhere, that why I had a problem with it only with tools

2021-01-16 22:48 UTC, HarrievG commented
> At some time after the next release I wanna try to get rid of libogg/vorbis(file) and libjpeg and zlib and replace them with header-only libs (stb_vorbis, stb_image and miniz).
> So the only remaining dependencies will be SDL2, OpenAL and (optionally) libcurl, and of course the C and C++ standardlibs.
> That should make building less painful (though of course especially the combination of SDL2 and CMake might still cause us pain)
> 
> I hope I get that release done soon(ish), but there's still some things to do.
> 
> To be honest, I also think that I won't merge this change before the release. Don't get me wrong, the 4K fixes for the tools look great and I really want them, but both them and the cmake changes look quite invasive and I don't want to risk breaking anything that worked so far shortly before a release.
> 
> Once this branch is in a state that works for me on both Linux and Windows, I'll create a branch based on it (and the then-current master) so you have a sane base for further work (even _if_ I don't get the fscking 1.5.1 release done).

I will take out the casing . No problem. I will also try to setup Travis to build it so I can catch any other build related things. That hopefully will mitigate some risks.

If there is anything I can do to help with 1.5.1 just assign me some bugs and I'll do all that I can.

2021-01-17 05:45 UTC, DanielGibson commented
> If there is anything I can do to help with 1.5.1 just assign me some bugs and I'll do all that I can.

Thanks for the offer!
There's two bugs I'd like to fix before release if it's small/harmless (-looking) fixes: #295 #331

Apart from that I'll have to do some work on the mods (https://github.com/dhewm/dhewm3-sdk), like
* update them with relevant changes done in the dhewm3 repo
* try to fix Dentonmod crashes (IIRC Rivensin is based on Dentonmod and I already fixed lots of bugs there, I'll have to see what of those fixes apply to Dentonmod and port them)

2021-01-17 06:02 UTC, DanielGibson commented
Oh, another thing that would be nice to have for the next release is #318
I already implemented it for POSIX (Linux etc), but Windows is still missing: https://github.com/DanielGibson/dhewm3/tree/dll-load-errors.

2021-01-17 09:45 UTC, HarrievG commented
Yes, let me take those windows specific ones, its my main platform anyway, so i gladly go look at #318 .

2021-04-21 14:00 UTC, HarrievG commented
Hi Daniel,
was there something else here you wanted to be done before merging?

I want to create pull requests, for the debugger too, but it layers on top of this.
Besides that  i see that @Stradex is refactoring some code which will have impact on the debugger implementation, and i dont want to much divergence :P 

cheers!
-H

2021-04-21 18:41 UTC, DanielGibson commented
Right now this branch can't be merged, the first step would be to rebase it onto the current master branch

2021-04-22 09:39 UTC, turol commented
Not really refactoring, #369 is pretty much all of it. It's only a draft because I'm not sure it's a good idea and I know you were also doing something to it. My changes are mostly mechanical and I'm fine with you either incorporating them or doing something totally different.

2021-04-22 18:53 UTC, HarrievG commented
@DanielGibson  first step complete!?

2021-04-22 19:08 UTC, DanielGibson commented
Can you please **rebase** it so we don't have all those "merge master into upstream" commits in the history?

2021-04-22 19:11 UTC, HarrievG commented
uhm yes! crap! wrong button :S

2021-04-22 20:25 UTC, HarrievG commented
not sure what i did wrong now.
But it looks like i have som work left:

- [ ] Put back @turol changes ( no idea why they are reverted, auto merge during rebase maybe?)
- [ ] Remove all the QGL, IMGUI and DAE stuff.

2021-04-22 20:32 UTC, turol commented
Well that's quite a mess... You're probably better off creating a new branch off the current master and cherry-picking the appropriate commits into it.

Also, https://xkcd.com/1597/

2021-04-22 20:40 UTC, HarrievG commented
Lol. yeah well. i "remembered" the revert command ;P

I just keep trying to use git as Perforce (Muscle Memory) . But it isnt perforce, and it will never behave like it either, i just have to remember the wise words : "BRANCH FIRST"

Yeah, will cherry pick..

2021-05-06 01:37 UTC, DanielGibson commented
oh shit, I totally didn't think about this when I just merged #376 - I fear there will be merge conflicts

2021-05-06 05:30 UTC, HarrievG commented
This bs.
I am trying to get this is for ages.

On Thu, May 6, 2021, 03:37 Daniel Gibson ***@***.***> wrote:

> oh shit, I totally didn't think about this when I just merged #376
> <https://github.com/dhewm/dhewm3/pull/376> - I fear there will be merge
> conflicts
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dhewm/dhewm3/pull/339#issuecomment-833161466>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIUHNRXLYV2KMYBOFG6H2DTMHXFVANCNFSM4WEWWUIA>
> .
>

2021-05-06 05:43 UTC, HarrievG commented
I cannot reconcile with this. I really have done a lot of work. 

So let's try to solve it.

If you help me merging this and getting it in, ( rang me up, walk me through it, really. ), so that my git skills are enough to not have to spend so much time getting it upstream again then everybody wins.

And then I can _finally_ integrate the debugger too. So frigging proud of that one. Not going to let that go to waste, even that Id guy I asked if it was actually allowed to gpl it (because of raven Software) was impressed.

2021-05-06 08:47 UTC, turol commented
I think you almost got it, there's just two extraneous commits remaining. The following should give you a branch without them:
```
git checkout -b newBranch 9e316ac0d6d9ddb565ca5929d1d9cb35dd92ba94
```

2021-05-06 14:07 UTC, DanielGibson commented
> 1. That guy did not pay attention the source tree.

I don't really get what you mean, his changes looked clean and only did what needed (replacing all that WindowLong shit with WindowLongPtr so it works with 64bit pointers as well)

> I am trying to get this in for ages.
> 2. Why did I have to wait 3, almost 4 months , and this is going in like a snap.

I would have merged this after 1.5.1 if the branch had been clean - his branch was just one commit, no superfluous or even duplicate commits like this one.
I can help you with getting this cleaned up in git via discord if you want.

2021-05-07 02:32 UTC, DanielGibson requested changes
just as a reminder about that get DPI wrapper

2021-05-09 01:07 UTC, HarrievG commented on neo/tools/radiant/InspectorDialog.cpp
> +	UINT dpi = GetDpiForWindow(GetSafeHwnd());
Done.
use Devicecaps on anything less then win10 !
needs to be tweaked and tested on the lesser win versions.

2021-05-10 02:29 UTC, DanielGibson commented
I added dynamic loading of the dpi getting function to support older windows versions again, see https://github.com/dhewm/dhewm3/commits/tool-dpi-scaling - if that works I'll merge it.

Win64 binaries with all this: [dhewm3-1.5.2pre-win64-tools-dpiscale.zip](https://github.com/dhewm/dhewm3/files/6449046/dhewm3-1.5.2pre-win64-tools-dpiscale.zip)

2021-05-10 05:48 UTC, HarrievG commented
Whoo ! 

Very happy with the end result, thx for adding the win 8 method!

This is now solid as a rock. 

😀

2021-05-10 06:34 UTC, DanielGibson approved these changes

2021-05-10 06:38 UTC, DanielGibson commented
these changes are now in master - thanks a lot! :)

2021-05-10 06:38 UTC, closed without merging